// ===========================================================================
//  Data-point tags — the "answer key" symbol system for the Sources detail
//  panel. Every data point (across all three tiers) can carry one or more of
//  these tags so the owner can see, at a glance, WHAT KIND of data it is and
//  how to organize / handle it. Pure reference data — edit ITEM_TAGS to
//  reclassify any point; the icons follow automatically.
// ===========================================================================

export type DataTag = "person" | "vehicle" | "key" | "pii" | "aggregate" | "money" | "trigger" | "quality";
export type EffortTag = "config" | "dev" | "paid";

export const TAG_META: Record<DataTag, { icon: string; label: string; desc: string }> = {
  person: { icon: "👤", label: "Person", desc: "Belongs in the individual seller's Customer-360 profile." },
  vehicle: { icon: "🚗", label: "Vehicle / deal", desc: "About the car or the deal on it — its own record, joined to the person by VIN." },
  key: { icon: "🔑", label: "Join key", desc: "An identity or join key that stitches records together (email, phone, visitor id, VIN, campaign…)." },
  pii: { icon: "🔒", label: "Sensitive / PII", desc: "Personal + consent-sensitive (CASL) — mask and store carefully." },
  aggregate: { icon: "📊", label: "Aggregate", desc: "Reporting only — counts / rates / breakdowns; never merge into an individual profile." },
  money: { icon: "💰", label: "Money / margin", desc: "Financial — feeds your P&L (offer, buy, resale, spend, ROAS, reward)." },
  trigger: { icon: "⚡", label: "Real-time trigger", desc: "Should fire an action now (hot lead, reply detected), not just sit in a report." },
  quality: { icon: "🛡️", label: "Quality / fraud", desc: "A lead-quality or fraud-filtering signal (VPN, bot, mismatch, dead number)." },
};

export const EFFORT_META: Record<EffortTag, { icon: string; label: string; desc: string }> = {
  config: { icon: "⚙️", label: "Config-only", desc: "A setting / toggle to switch on — quick win." },
  dev: { icon: "🔧", label: "Needs dev", desc: "Requires building / coding." },
  paid: { icon: "💵", label: "Paid tier", desc: "Needs a paid plan or add-on to unlock." },
};

/** Render order so an item's icons always appear in a consistent sequence. */
export const TAG_ORDER: DataTag[] = ["person", "vehicle", "key", "money", "pii", "quality", "trigger", "aggregate"];

/** sourceId → exact item label → its tags (+ effort, for "could collect" items).
 * Populated from a per-source tagging pass; edit any entry to reclassify. */
export const ITEM_TAGS: Record<string, Record<string, { tags: DataTag[]; effort?: EffortTag }>> = {
  leads: {
    "Name, email, phone": { tags: ["person", "key", "pii"] },
    "Preferred contact method + best time": { tags: ["person"] },
    "Vehicle: year, make, model, trim, mileage": { tags: ["vehicle"] },
    "Condition tags + free-text note": { tags: ["vehicle"] },
    "Marketing attribution (UTM, gclid, fbclid, referrer)": { tags: ["person", "key"] },
    "On-site behavior (visits, funnel step, time on site)": { tags: ["person"] },
    "Meta match keys (fbp / fbc) + GA client/session id": { tags: ["person", "key"] },
    "Best-time-to-call windows": { tags: ["person"] },
    "Condition note free-text": { tags: ["vehicle"] },
    "Return-visitor count": { tags: ["person"] },
    "UTM-to-vehicle patterns": { tags: ["aggregate"] },
    "fbc/fbp offline value": { tags: ["person", "key", "money"] },
    "Time-on-site as intent": { tags: ["person", "trigger"] },
    "Field-level timing & hesitation": { tags: ["person"], effort: "dev" },
    "Abandoned-form partial capture": { tags: ["person", "trigger"], effort: "dev" },
    "Input method detection": { tags: ["person", "quality"], effort: "dev" },
    "IP geolocation to city": { tags: ["person", "pii", "quality"], effort: "paid" },
    "Asking-price expectation": { tags: ["vehicle", "money"], effort: "config" },
    "VIN or license plate": { tags: ["vehicle", "key"], effort: "config" },
    "Payoff / lien status": { tags: ["vehicle", "money"], effort: "config" },
    "Reason & timeline to sell": { tags: ["person", "trigger"], effort: "config" },
    "Photo upload of the car": { tags: ["vehicle"], effort: "dev" },
  },
  partials: {
    "Partial contact (name / email / phone as typed)": { tags: ["person", "key", "pii"] },
    "Partial vehicle info": { tags: ["vehicle"] },
    "Attribution + behavior": { tags: ["person", "key"] },
    "Whether an owner alert was already sent": { tags: ["person"] },
    "Last field before exit": { tags: ["person"] },
    "Partial phone = callable lead": { tags: ["person", "key", "pii", "trigger"] },
    "Vehicle info without contact": { tags: ["vehicle"] },
    "Attribution on abandoners": { tags: ["person", "key"] },
    "Owner-alert-sent flag": { tags: ["person"] },
    "Step reached at exit": { tags: ["person"] },
    "Time spent per field": { tags: ["person"], effort: "dev" },
    "Correction / retype rate": { tags: ["person"], effort: "dev" },
    "Validation errors hit": { tags: ["person", "quality"], effort: "dev" },
    "Field completion order": { tags: ["person"], effort: "dev" },
    "Device and input type": { tags: ["person"], effort: "dev" },
    "Scroll depth / CTA seen": { tags: ["person"], effort: "dev" },
    "Focus/blur tab-switching": { tags: ["person"], effort: "dev" },
    "Price-expectation as typed": { tags: ["person", "vehicle", "money"], effort: "dev" },
    "Repeat-visitor abandonment": { tags: ["person"], effort: "dev" },
  },
  events: {
    "Page views + route changes": { tags: ["person"] },
    "Funnel steps (offer_flow_start → generate_lead)": { tags: ["person"] },
    "Field focus / blur + form errors": { tags: ["person", "quality"] },
    "VIN decode funnel": { tags: ["person", "vehicle"] },
    "Exit-intent + resume prompts": { tags: ["person", "trigger"] },
    "Session + visitor ids": { tags: ["person", "key"] },
    "Field re-edit & hesitation": { tags: ["person", "quality"] },
    "Time-per-funnel-step": { tags: ["person"] },
    "VIN decode drop-off point": { tags: ["aggregate", "vehicle"] },
    "Form-error field ranking": { tags: ["aggregate"] },
    "Resume-prompt conversion rate": { tags: ["aggregate"] },
    "Returning-visitor journey stitch": { tags: ["person", "key"] },
    "Scroll depth on offer page": { tags: ["person"], effort: "dev" },
    "Rage & dead clicks": { tags: ["person", "quality"], effort: "dev" },
    "Device, viewport & OS": { tags: ["person"], effort: "config" },
    "Referrer & UTM on event": { tags: ["person", "key"], effort: "config" },
    "Copy-to-clipboard & phone tap": { tags: ["person", "trigger"], effort: "dev" },
    "Photo-upload interaction": { tags: ["person", "vehicle"], effort: "dev" },
    "Field autofill vs typed": { tags: ["person", "quality"], effort: "dev" },
    "Estimate/slider engagement": { tags: ["person", "vehicle"], effort: "dev" },
    "Session-level intent score": { tags: ["person", "trigger"], effort: "dev" },
  },
  attribution: {
    "UTM source / medium / campaign / content / term": { tags: ["person", "key"] },
    "Google click id (gclid)": { tags: ["person", "key"] },
    "Meta click id (fbclid)": { tags: ["person", "key"] },
    "External referrer + landing page": { tags: ["person"] },
    "Full multi-touch journey (oldest → newest)": { tags: ["person"] },
    "First- vs last-touch split": { tags: ["aggregate"] },
    "Time-to-conversion window": { tags: ["person"] },
    "Touch count per lead": { tags: ["person"] },
    "Landing page path patterns": { tags: ["aggregate"] },
    "gclid campaign-side join": { tags: ["person", "key"] },
    "Referrer-quality segmentation": { tags: ["aggregate", "quality"] },
    "Keyword + match type": { tags: ["person", "aggregate"], effort: "config" },
    "Device type at click": { tags: ["person"], effort: "config" },
    "Physical location ID": { tags: ["person", "key"], effort: "config" },
    "Network + placement": { tags: ["person", "aggregate"], effort: "config" },
    "gbraid / wbraid capture": { tags: ["person", "key"], effort: "dev" },
    "Ad creative + campaign ID": { tags: ["person", "key"], effort: "config" },
    "Server-side first-party store": { tags: ["person", "key"], effort: "dev" },
    "Cross-device stitch key": { tags: ["person", "key"], effort: "dev" },
    "Session count before form": { tags: ["person"], effort: "dev" },
  },
  lookups: {
    "Vehicle looked up": { tags: ["vehicle"] },
    "Outcome (priced range vs unique / no-price)": { tags: ["vehicle"] },
    "Estimate range shown": { tags: ["vehicle", "money"] },
    "MarketCheck API calls used + cache hits": { tags: ["aggregate"] },
    "Whether it converted to a lead": { tags: ["person"] },
    "Priced-but-didn't-convert list": { tags: ["aggregate"] },
    "Estimate-range width": { tags: ["vehicle", "money"] },
    "MarketCheck comp count": { tags: ["vehicle", "aggregate"] },
    "Cache-hit repeat lookups": { tags: ["aggregate"] },
    "Priced-vs-unique split by model": { tags: ["vehicle", "aggregate"] },
    "Estimate vs actual-buy gap": { tags: ["vehicle", "money", "aggregate"] },
    "Market Days Supply": { tags: ["vehicle", "aggregate"], effort: "paid" },
    "Trim and options decode": { tags: ["vehicle"], effort: "paid" },
    "VIN price history": { tags: ["vehicle", "key", "money"], effort: "paid" },
    "Mileage entered at lookup": { tags: ["vehicle"], effort: "dev" },
    "Lookup-to-form drop-off point": { tags: ["aggregate"], effort: "dev" },
    "Regional Alberta comps": { tags: ["vehicle", "money", "aggregate"], effort: "paid" },
    "Estimate acceptance sentiment": { tags: ["aggregate"], effort: "dev" },
    "Seasonal price trend": { tags: ["money", "aggregate"], effort: "dev" },
    "Vehicle popularity/rarity score": { tags: ["vehicle", "aggregate"], effort: "dev" },
  },
  referrals: {
    "Referrer name / email / phone": { tags: ["person", "key", "pii"] },
    "Friend name / phone / email": { tags: ["person", "key", "pii"] },
    "Message": { tags: ["person"] },
    "Generated referral code": { tags: ["key"] },
    "Attribution + behavior": { tags: ["person"] },
    "Referrer as repeat seller": { tags: ["person"] },
    "Friend contact = warm lead": { tags: ["person", "trigger"] },
    "Referral code redemption status": { tags: ["person"] },
    "Referrer's own attribution": { tags: ["person"] },
    "Referral message intent": { tags: ["person"] },
    "Referrer-friend relationship graph": { tags: ["person", "key"] },
    "Share channel used": { tags: ["person"], effort: "dev" },
    "Referred car details": { tags: ["vehicle"], effort: "dev" },
    "Double-sided reward payout": { tags: ["money"], effort: "dev" },
    "Reward eligibility gating": { tags: ["money"], effort: "dev" },
    "Self-referral / fraud flags": { tags: ["quality"], effort: "dev" },
    "Referral link click tracking": { tags: ["person", "key"], effort: "dev" },
    "Referrer leaderboard / tiers": { tags: ["aggregate"], effort: "dev" },
    "Time-to-referral latency": { tags: ["aggregate"], effort: "dev" },
    "Referral consent capture": { tags: ["person", "pii"], effort: "dev" },
  },
  chat: {
    "Conversation + message history": { tags: ["person", "trigger"] },
    "Visitor name + contact": { tags: ["person", "key", "pii"] },
    "Who replied last (the needs-reply cue)": { tags: ["person", "trigger"] },
    "Pages viewed pre-chat": { tags: ["person"] },
    "Current page context": { tags: ["person"] },
    "Geo from IP": { tags: ["person", "pii", "quality"] },
    "Returning vs new visitor": { tags: ["person"] },
    "Referrer and search terms": { tags: ["person", "key"] },
    "Chat-to-lead linkage": { tags: ["person", "key"] },
    "Pre-chat vehicle form": { tags: ["vehicle", "person"], effort: "config" },
    "Post-chat CSAT rating": { tags: ["person", "quality"], effort: "config" },
    "Chat tags/dispositions": { tags: ["person", "quality"], effort: "config" },
    "Proactive price-page trigger": { tags: ["trigger"], effort: "config" },
    "Offline lead-capture form": { tags: ["person", "key", "pii"], effort: "config" },
    "Missed-chat tracking": { tags: ["trigger", "aggregate"], effort: "config" },
    "Canned offer responses": { tags: ["money"], effort: "dev" },
    "First-response time metric": { tags: ["aggregate"], effort: "dev" },
    "Device and OS": { tags: ["person", "quality"], effort: "config" },
  },
  geo: {
    "Country / province / city": { tags: ["person"] },
    "Resolved-at timestamp": { tags: ["person"] },
    "Postal / FSA code": { tags: ["person", "pii"] },
    "Latitude / longitude": { tags: ["person", "pii"] },
    "ISP / connection org": { tags: ["person", "quality"] },
    "Timezone vs. form time": { tags: ["person", "quality"] },
    "IP-city vs. stated city": { tags: ["person", "quality"] },
    "VPN / proxy / Tor flag": { tags: ["person", "quality"], effort: "paid" },
    "Hosting / datacenter flag": { tags: ["person", "quality"], effort: "paid" },
    "Fraud / abuse score": { tags: ["person", "quality"], effort: "paid" },
    "Mobile vs. fixed line": { tags: ["person", "quality"], effort: "paid" },
    "Accuracy radius": { tags: ["person", "quality"], effort: "paid" },
    "Reverse hostname (PTR)": { tags: ["person", "quality"], effort: "dev" },
    "ASN-based repeat detection": { tags: ["person", "key", "quality"], effort: "dev" },
    "Currency / calling code": { tags: ["person"], effort: "config" },
  },
  metaAds: {
    "Campaign & ad spend (CAD)": { tags: ["aggregate", "money"] },
    "Impressions, reach, link clicks, CTR": { tags: ["aggregate"] },
    "Leads + cost-per-lead": { tags: ["aggregate", "money"] },
    "Creative hook / hold video metrics": { tags: ["aggregate"] },
    "Region + DMA breakdown": { tags: ["aggregate"] },
    "Hourly performance breakdown": { tags: ["aggregate"] },
    "Placement-level cost-per-lead": { tags: ["aggregate", "money"] },
    "Age & gender of leads": { tags: ["aggregate"] },
    "Frequency by ad": { tags: ["aggregate"] },
    "Ad relevance diagnostics": { tags: ["aggregate", "quality"] },
    "Offline conversion upload": { tags: ["person", "key", "money"], effort: "dev" },
    "Value-based lookalike audiences": { tags: ["aggregate", "money"], effort: "config" },
    "CRM custom-audience sync": { tags: ["person", "key", "pii"], effort: "dev" },
    "Suppression of bought sellers": { tags: ["person", "key"], effort: "dev" },
    "Audience match rate": { tags: ["aggregate"], effort: "config" },
    "Estimated ad recall lift": { tags: ["aggregate"], effort: "paid" },
    "Creative asset breakdown": { tags: ["aggregate"], effort: "config" },
    "Lead Ads instant forms": { tags: ["person", "pii", "trigger"], effort: "dev" },
    "Ad-level UTM & ad ID join": { tags: ["person", "key"], effort: "dev" },
  },
  ga4Data: {
    "Users, new users, sessions, page views": { tags: ["aggregate"] },
    "Engagement rate": { tags: ["aggregate"] },
    "Traffic by source / medium": { tags: ["aggregate"] },
    "By country + device": { tags: ["aggregate"] },
    "Landing page performance": { tags: ["aggregate"] },
    "Source/medium by conversion": { tags: ["aggregate"] },
    "City and region breakdown": { tags: ["aggregate"] },
    "New vs returning behavior": { tags: ["aggregate"] },
    "Engagement rate by segment": { tags: ["aggregate"] },
    "Device category conversion gap": { tags: ["aggregate"] },
    "Form-funnel key events": { tags: ["aggregate", "trigger"], effort: "dev" },
    "Landing page + query string": { tags: ["person", "key"], effort: "config" },
    "Hour and day-of-week": { tags: ["aggregate"], effort: "config" },
    "Session campaign name": { tags: ["person", "key"], effort: "config" },
    "Scroll depth on offer page": { tags: ["person", "trigger"], effort: "dev" },
    "Estimate value as event value": { tags: ["vehicle", "money"], effort: "dev" },
    "Session default channel group": { tags: ["person"], effort: "config" },
    "Cohort / retention report": { tags: ["aggregate"], effort: "config" },
    "Site-search terms": { tags: ["aggregate"], effort: "config" },
  },
  marketcheck: {
    "VIN → year / make / model / trim": { tags: ["vehicle", "key"] },
    "Market asking-price percentiles": { tags: ["vehicle", "aggregate", "money"] },
    "Active listing counts by trim": { tags: ["vehicle", "aggregate"] },
    "NeoVIN factory options": { tags: ["vehicle"], effort: "config" },
    "Market days-supply": { tags: ["vehicle", "aggregate"] },
    "Active listing DOM": { tags: ["vehicle", "aggregate"] },
    "Comparable price percentiles": { tags: ["vehicle", "aggregate", "money"] },
    "Mileage vs the market": { tags: ["vehicle", "aggregate"] },
    "Predicted price + MSRP gap": { tags: ["vehicle", "money"] },
    "Private-party (FSBO) comps": { tags: ["vehicle", "aggregate", "money"], effort: "paid" },
    "VIN price-change history": { tags: ["vehicle", "money"], effort: "paid" },
    "Auction listing prices": { tags: ["vehicle", "aggregate", "money"], effort: "paid" },
    "Dealer-comp geolocation": { tags: ["vehicle", "aggregate"], effort: "dev" },
    "Residual-value depreciation": { tags: ["vehicle", "money"], effort: "paid" },
    "Popular-vehicles demand": { tags: ["vehicle", "aggregate"], effort: "paid" },
    "Full NeoVIN spec + MPG": { tags: ["vehicle"], effort: "config" },
    "Recall / build flags": { tags: ["vehicle"], effort: "dev" },
    "Sales statistics trend": { tags: ["vehicle", "aggregate"], effort: "paid" },
  },
  gtag: {
    "Page views + route changes": { tags: ["person"] },
    "Funnel + click events (mirrored to GA4)": { tags: ["person"] },
    "GA client id / session id (the _ga cookie)": { tags: ["person", "key"] },
    "Alberta city/region geo": { tags: ["person"] },
    "Session source / medium": { tags: ["person"] },
    "Scroll-depth on landing pages": { tags: ["person"] },
    "Device category split": { tags: ["person"] },
    "Engagement time per step": { tags: ["person"] },
    "Outbound & tel: clicks": { tags: ["person", "trigger"] },
    "Vehicle params on events": { tags: ["vehicle"], effort: "dev" },
    "Lead-value on submit": { tags: ["person", "money"], effort: "dev" },
    "Offer/booking as conversions": { tags: ["money"], effort: "config" },
    "User-scoped lead status": { tags: ["person"], effort: "dev" },
    "Condition/damage parameter": { tags: ["vehicle"], effort: "dev" },
    "Google Ads / signal linking": { tags: ["key"], effort: "config" },
    "Custom scroll & timing events": { tags: ["person"], effort: "dev" },
    "Predictive purchase probability": { tags: ["person", "aggregate"], effort: "paid" },
    "Form-error / validation events": { tags: ["person", "quality"], effort: "dev" },
  },
  pixel: {
    "PageView, Search, ViewContent, InitiateCheckout, Lead": { tags: ["person"] },
    "Meta browser cookies (fbp / fbc)": { tags: ["person", "key"] },
    "fbclid → server fbc": { tags: ["person", "key"] },
    "Value on Lead event": { tags: ["money"] },
    "Automatic Advanced Matching": { tags: ["person", "key", "pii"] },
    "ViewContent content_category": { tags: ["person", "vehicle"] },
    "Search query parameter": { tags: ["person", "vehicle"] },
    "InitiateCheckout drop-off": { tags: ["person", "trigger"] },
    "Contact standard event": { tags: ["person", "trigger"], effort: "dev" },
    "Schedule standard event": { tags: ["person", "trigger"], effort: "dev" },
    "Purchase on car bought": { tags: ["vehicle", "money"], effort: "dev" },
    "predicted_ltv parameter": { tags: ["person", "money"], effort: "dev" },
    "external_id matching": { tags: ["person", "key"], effort: "dev" },
    "CompleteRegistration event": { tags: ["person"], effort: "dev" },
    "AddPaymentInfo as offer-accept": { tags: ["person", "vehicle", "money", "trigger"], effort: "dev" },
    "Custom vehicle-segment events": { tags: ["person", "vehicle"], effort: "dev" },
    "FindLocation for service area": { tags: ["person"], effort: "dev" },
  },
  clarity: {
    "Session recordings + heatmaps": { tags: ["person", "pii"] },
    "Visitor id for stitching sessions": { tags: ["person", "key"] },
    "Never records typed form data (masked by default)": { tags: ["pii"] },
    "Rage & dead clicks": { tags: ["person"] },
    "Excessive / dead scrolling": { tags: ["person"] },
    "Quick-back sessions": { tags: ["person"] },
    "JavaScript error sessions": { tags: ["person"] },
    "Scroll-depth on form steps": { tags: ["person"] },
    "GA4 Clarity Playback URL": { tags: ["person", "key"] },
    "Identify leads by ID": { tags: ["person", "key"], effort: "dev" },
    "Custom tag: vehicle value": { tags: ["vehicle", "money"], effort: "dev" },
    "Custom tag: lead status": { tags: ["person"], effort: "dev" },
    "Custom tag: traffic source": { tags: ["person", "key"], effort: "dev" },
    "Smart event: offer viewed": { tags: ["person", "trigger"], effort: "dev" },
    "Upgrade high-intent sessions": { tags: ["person", "trigger"], effort: "paid" },
    "Booking-page funnel event": { tags: ["person", "trigger"], effort: "dev" },
    "Consent-gated recording": { tags: ["person", "pii"], effort: "config" },
    "Unmask non-sensitive fields": { tags: ["person"], effort: "config" },
  },
  email: {
    "Delivered / opened / clicked receipts": { tags: ["person"] },
    "Hard bounces + spam complaints (opt-out)": { tags: ["person", "quality"] },
    "Inbound customer replies (via the Gmail script)": { tags: ["person", "trigger"] },
    "Per-lead comms timeline": { tags: ["person"] },
    "Per-URL click data": { tags: ["person"] },
    "Time-to-open latency": { tags: ["person"] },
    "Open/click count per lead": { tags: ["person"] },
    "Delivery-delayed events": { tags: ["person"] },
    "Bounce reason surfacing": { tags: ["person", "quality"] },
    "Reply-detected auto-warm": { tags: ["person", "trigger"] },
    "Tag emails by stage": { tags: ["person"], effort: "dev" },
    "Tag offer price band": { tags: ["vehicle", "money"], effort: "dev" },
    "Idempotency keys": { tags: ["key"], effort: "dev" },
    "Native scheduled_at send": { tags: [], effort: "config" },
    "Audiences + contact properties": { tags: ["person"], effort: "dev" },
    "Managed unsubscribe/topics": { tags: ["person"], effort: "config" },
    "Broadcast open/click analytics": { tags: ["aggregate"], effort: "paid" },
    "Dedicated sending domain warmup": { tags: [], effort: "paid" },
    "Scheduled-send cancellation": { tags: [], effort: "config" },
  },
  sms: {
    "Delivered / failed receipts": { tags: ["person"] },
    "Inbound replies + 'C' confirmations": { tags: ["person", "trigger"] },
    "STOP / START opt-out state": { tags: ["person"] },
    "Per-lead comms timeline": { tags: ["person"] },
    "SMS error codes": { tags: ["person", "quality"] },
    "Reply latency + timing": { tags: ["person"] },
    "Inbound sender geo fields": { tags: ["person", "pii", "quality"] },
    "Message segment counts": { tags: ["aggregate", "money"] },
    "STOP-per-touchpoint context": { tags: ["person", "aggregate"] },
    "Confirmation keyword parsing": { tags: ["person", "trigger"] },
    "Line Type Intelligence lookup": { tags: ["person", "quality"], effort: "paid" },
    "Carrier + caller name": { tags: ["person", "pii", "quality"], effort: "paid" },
    "Link click tracking": { tags: ["person", "trigger"], effort: "dev" },
    "Scheduled offer messages": { tags: ["person"], effort: "dev" },
    "Inbound MMS photos": { tags: ["person", "vehicle"], effort: "dev" },
    "Messaging Insights analytics": { tags: ["aggregate"], effort: "config" },
    "Delivery-time-to-read gap": { tags: ["person"], effort: "dev" },
    "Keyword auto-responder": { tags: ["trigger"], effort: "dev" },
    "Number-reputation / 10DLC campaign data": { tags: ["aggregate", "quality"], effort: "config" },
  },
};

/** Tags for one data point (empty if untagged). */
export function tagsFor(sourceId: string, label: string): { tags: DataTag[]; effort?: EffortTag } {
  return ITEM_TAGS[sourceId]?.[label] ?? { tags: [] };
}
